---

- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat


- name: Initialize Kubernetes master with kubeadm init
  command: >
    kubeadm init
    --pod-network-cidr=10.244.0.0/16
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --ignore-preflight-errors=all
  register: kubeadmin_init
  when:
    - ansible_local.aws.kubernetes.mode == 'controller'
    - not kubernetes_init_stat.stat.exists


- name: Ensure .kube directory exists
  file:
    path: ~/.kube
    state: directory
    mode: 0755


- name: Symlink the kubectl admin.conf to ~/.kube/conf
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644


- name: Install flannel
  command: >
    kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
  register: kubeadmin_init
  when:
    - not kubernetes_init_stat.stat.exists


- name: Install ingress-nginx
  command: >
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/baremetal/deploy.yaml
  register: kubeadmin_init
  when:
    - not kubernetes_init_stat.stat.exists


- name: Get the kubeadm join command from the Kubernetes master
  command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result


- name: Set the kubeadm join command globally
  set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
