apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: add
      path: "/spec/ports/0/nodePort"
      value: 30171
  target:
    kind: Service
    name: ingress-nginx-controller

resources:
- hello.yaml
- http://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/baremetal/deploy.yaml
